<|"MutatingFunction" -> {"SymbolNameSet", "SymbolNameSetDelayed", 
   "UnprotectClear", "UnprotectClearAll"}, 
 "IOFunction" -> {"CachedBox", "CachePrint", "CreateCachedBox", 
   "CustomizedPrint", "DPrint", "EchoPrint", "EnsureContext", "ErrorPrint", 
   "ExportGroupsToKinds", "ExtractPreludeExports", "FileSymbolExports", 
   "FromInputString", "GetHidden", "GetHoldComplete", "HoldToInputString", 
   "LabeledPrint", "LoadPackage", "LogPrint", "RawPrint", 
   "SavePreludeExports", "SublimeOpen", "SublimeRun", "SublimeSeek", 
   "ToInputString", "WithRawPrintIndent"}, "DataHead" -> {"UAssociation"}, 
 "Function" -> {"CreateDynamicAlias", "DefaultPostEvaluationHook", 
   "DefaultPreEvaluationHook", "FindLikelySymbolName", "FullIntegerString", 
   "HoldByteCount", "HoldLength", "HoldSequenceLength", "HoldSymbolContext", 
   "HoldSymbolName", "HoldSymbolNameAlias", "HoldSymbolPath", 
   "InstallSessionHooks", "LikelySymbolNames", "LoadedPackages", "NameFirst", 
   "NameLast", "NameMost", "NameMostLast", "NamePaths", "NamePathsGrouped", 
   "NaturalNumberString", "PackageSymbolKinds", "PackageSymbolNames", 
   "RegisterDynamicAliasFunction", "RestoreEvaluationCellState", 
   "SaveEvaluationCellState", "UninstallSessionHooks", "UniqueSessionID"}, 
 "Predicate" -> {"ActiveNameQ", "ActiveSymbolQ", "CapitalizedSymbolQ", 
   "CoreToolsContextQ", "CoreToolsSymbolQ", "DocumentedSymbolQ", 
   "FormalSymbolQ", "HoldAssociationQ", "HoldBooleanQ", "HoldIntegerQ", 
   "HoldListQ", "HoldNaturalQ", "HoldNumberQ", "HoldPackedArrayQ", 
   "HoldStringQ", "InertSymbolQ", "InertSystemSymbolQ", "InertUserSymbolQ", 
   "PackageLoadCompletedQ", "PackedListQ", "SessionEvaluatedSinceQ", 
   "SystemContextQ", "SystemSymbolQ", "UserSymbolQ"}, 
 "Variable" -> {"$CurrentEvaluationCellState", "$EvaluationsSinceDict", 
   "$ExportSymbolKinds", "$FormalSymbols", "$LastFailedExpression", 
   "$PackageCurrentlyLoading", "$PackageLoadCompleteQ", 
   "$PackageLoadVerbose", "$PreludeDir", 
   "$SessionCurrentEvaluationPrintCount", 
   "$SessionCurrentEvaluationStartTime", "$SessionEvaluationsCount", 
   "$SessionLastEvaluationTime", "$SessionMaxEvaluationPrintCount", 
   "$SublimeApplicationPath", "$SublimeProjectsPath", "$SublimeRunCount", 
   "$SymbolAliases"}, "ControlFlowFunction" -> 
  {"PrivateHoldComplete", "PrivateHoldCompleteSequence", "PrivateSequence"}, 
 "SymbolicHead" -> {"AttachDelayedValue", "AttachImmediateValue", 
   "FileExportGroup"}, "Option" -> {"Caching", "Logging", "LogLevel", 
   "OpenInNewWindow", "SublimeProject", "Verbose"}, 
 "FormHead" -> {"SourceLocation"}, "PackageFunction" -> 
  {"DeclareFileLocals", "DeclareFilePrivates", "DeclarePackageGlobals", 
   "DeclarePackageLocals", "DeclarePackagePrivates", "DeclareSystemGlobals", 
   "DeclareSystemPrivates", "PackageExports", "PrivateExports", 
   "SystemExports"}, "MessageFunction" -> 
  {"LoadPrint", "NonLethalPackageMessages", "PackageLoadMessageHandler", 
   "PackageLoadShadowMessageHandler", "PackageLoadUncaughtThrowHandler"}, 
 "DebuggingFunction" -> {"AbortPackageLoading", "BenchmarkUnpacking", 
   "BenchmarkUnpackingData", "BlockPrint", "Capture", "CountUnpackings", 
   "DisableEchoPrinting", "EnableDebugPrinting", "FailureString", 
   "HandleUnpacking", "MicroTiming", "MicroTimingTable", "RawPrintBoxes", 
   "TraceAutoloads", "TraceUnpackings", "UnpackingTable", "UnpacksDuringQ"}, 
 "SpecialVariable" -> {"$CachePrinting", "$Captured", "$CellPrintLabel", 
   "$CurrentlyTracingAutoloads", "$CurrentPackageDirectory", 
   "$CurrentPackageExpr", "$CurrentPackageExprCount", "$CurrentPackageFile", 
   "$CurrentPackageFileHash $CurrentPackageExpr", 
   "$CurrentPackageLineSentinel", "$CurrentPackageMessageCount", 
   "$DebugPrinting", "$Disabled", "$EchoPrinting", "$LastTraceback", 
   "$LethalPackageMessages", "$PackageFileCache", "$PackageFileModTime", 
   "$PackageKindDeclarations", "$PackageLoadFileTimings", "$PackageModTime", 
   "$PackagePostLoadActions", "$PackagePreLoadActions", 
   "$PackageSymbolAliases", "$PackageSymbolTable", "$PostEvaluationHook", 
   "$PreEvaluationHook", "$RawPrintIndent", "$RawPrintMaxRate", 
   "$ShiftReturnHookInstalled", "$ShouldPrint", "$SymbolAliasesDirty"}, 
 "Head" -> {"FileLocation"}, "SpecialFunction" -> 
  {"DefinitionCounts", "DefinitionRules", "KernelCodes", "NewSymbolHandler"}|>
